import '@testing-library/jest-dom';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

// 테스트 환경에서 i18n 초기화 (한국어 번역으로 고정)
i18n.use(initReactI18next).init({
  resources: {
    ko: {
      translation: {
        common: {
          save: '저장',
          saving: '저장 중...',
          cancel: '취소',
          delete: '삭제',
          deleting: '처리 중...',
          edit: '수정',
          add: '추가',
          confirm: '확인',
          close: '닫기',
          loading: '로딩 중...',
        },
        auth: {
          login: '로그인',
          signup: '회원가입',
          logout: '로그아웃',
          email: '이메일',
          password: '비밀번호',
          name: '이름',
          emailPlaceholder: '이메일 주소',
          passwordPlaceholder: '비밀번호',
          namePlaceholder: '이름 입력',
          loginButton: '로그인',
          signupButton: '회원가입',
          goToSignup: '회원가입',
          goToLogin: '로그인',
          alreadyHaveAccount: '이미 계정이 있으신가요?',
          noAccount: '계정이 없으신가요?',
          errors: {
            invalidEmail: '올바른 이메일 형식이 아닙니다.',
            invalidPassword: '비밀번호는 8자 이상, 영문과 숫자를 포함해야 합니다.',
            loginFailed: '이메일 또는 비밀번호를 확인해주세요.',
            duplicateEmail: '이미 사용 중인 이메일입니다.',
          },
        },
        nav: {
          todos: '할일',
          categories: '카테고리',
          profile: '내 정보',
        },
        todo: {
          title: '할일 목록',
          addTodo: '할일 추가',
          emptyMessage: '할일이 없습니다.',
          titleLabel: '제목',
          titlePlaceholder: '할일 제목을 입력하세요',
          descriptionLabel: '설명',
          descriptionPlaceholder: '설명 (선택)',
          startDateLabel: '시작일',
          endDateLabel: '종료일',
          categoryLabel: '카테고리',
          statusLabel: '상태',
          categoryDefault: '카테고리 선택',
          addTitle: '할일 추가',
          editTitle: '할일 수정',
          deleteConfirmTitle: '할일 삭제',
          deleteConfirmMessage: '정말 삭제하시겠습니까? 이 작업은 취소할 수 없습니다.',
          status: {
            NOT_STARTED: '미시작',
            IN_PROGRESS: '진행중',
            DONE: '완료',
          },
          filter: {
            category: '카테고리',
            status: '상태',
            all: '전체',
            overdue: '기한 초과',
            allCategories: '전체 카테고리',
            allStatuses: '전체 상태',
          },
          overdue: '기한초과',
          errors: {
            titleRequired: '제목을 입력해주세요.',
            endDateInvalid: '종료일은 시작일 이후여야 합니다.',
          },
        },
        category: {
          title: '카테고리 관리',
          addCategory: '카테고리 추가',
          namePlaceholder: '카테고리 이름',
          defaultBadge: '기본',
          deleteConfirmTitle: '카테고리 삭제',
          deleteConfirmMessage: '해당 카테고리의 할일이 기본 카테고리로 이동됩니다.',
          errors: {
            nameRequired: '카테고리 이름을 입력해주세요.',
          },
        },
        profile: {
          title: '내 정보',
          nameSection: '이름 변경',
          passwordSection: '비밀번호 변경',
          languageSection: '언어 설정',
          deleteSection: '회원 탈퇴',
          email: '이메일',
          name: '이름',
          namePlaceholder: '이름 입력',
          newPassword: '새 비밀번호',
          newPasswordPlaceholder: '새 비밀번호 (8자 이상, 영문+숫자)',
          confirmPassword: '새 비밀번호 확인',
          confirmPasswordPlaceholder: '새 비밀번호 재입력',
          languageLabel: '언어',
          deleteButton: '회원 탈퇴',
          deleteDesc: '탈퇴 시 모든 할일과 카테고리가 영구 삭제됩니다.',
          deleteConfirmTitle: '회원 탈퇴',
          deleteConfirmMessage: '탈퇴하시겠습니까? 모든 데이터가 영구 삭제됩니다.',
          deletePasswordLabel: '비밀번호 확인',
          deletePasswordPlaceholder: '현재 비밀번호 입력',
          language: {
            ko: '한국어',
            en: 'English',
          },
          errors: {
            passwordMismatch: '새 비밀번호가 일치하지 않습니다.',
            passwordRequired: '비밀번호를 입력해주세요.',
            saveFailed: '저장에 실패했습니다.',
            deleteFailed: '탈퇴에 실패했습니다.',
          },
        },
      },
    },
  },
  lng: 'ko',
  fallbackLng: 'ko',
  interpolation: { escapeValue: false },
});
